#!/data/data/com.termux/files/usr/bin/bash
url=$1
echo "What should I do with $url ?"
echo "v) download video with yt-dlp"
echo "a) download video with yt-dlp and convert it to audio"
echo "c) choose quality of video"
echo "w) wget file to download-folder" 
echo "x) nothing"

read CHOICE
case $CHOICE in
	v)
                echo "downloading video at best quality..."
		yt-dlp --no-mtime --embed-metadata --embed-subs --embed-chapters -o "/sdcard/Termux/Video/%(title)s.%(ext)s" $url
		;;
	c)
		echo "Quality : "
		read q
                echo "downloading video at $q quality..."
		yt-dlp -f "bv[height<=$q]+ba" --no-mtime --embed-metadata --embed-subs --embed-chapters -o "/sdcard/Termux/Video/%(title)s.%(ext)s" $url
		;;
	a)
		echo "downloading audio..."
		yt-dlp -x --no-mtime --embed-thumbnail --embed-metadata -o "/sdcard/Termux/Audio/%(title)s.%(ext)s" $url
		;;
	w)
		cd ~/storage/downloads
		wget $url
		;;
	x)
		echo "bye"
		;; 
esac
